language:
  - java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/72d92f6ecbc9b66f264c
    on_success: change
    on_failure: always
before_script:
  - nvm install v5.5.0
  - nvm use v5.5.0
script: ./gradlew user:test
after_success:  ./gradlew user:jacocoTestReport user:coveralls 

