language:
  - java
  - node_js
jdk:
  - oraclejdk8
node_js:
  - "0.12.4"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/72d92f6ecbc9b66f264c
    on_success: change
    on_failure: always
script: ./gradlew setupUiDev testAll
after_script:  gradle jacocoTestReport coveralls 

