os:
  - linux
language: java
jdk:
  - oraclejdk11
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/72d92f6ecbc9b66f264c
    on_success: change
    on_failure: always

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - nvm install v10.19.0
  - nvm use v10.19.0

stages:
  - compile
  - style
  - test

jobs:
  include:
    - stage: compile
      name: "main java"
      script: ./gradlew compileJava
    - script: ./gradlew compileTestJava
      name: "test java"
    - script:
      - cd ui
      - yarn install
      - yarn build
      name: "main javascript"
    - stage: style
      name: "pmd"
      script:
        - ./gradlew pmdMain
        - ./gradlew pmdTest
    - script: ./gradlew checkstyle
      name: "checkstyle"
    - script:
      - cd ui
      - yarn install
      - yarn p:check
      name: "prettier"
    - stage: test
      name: "unit"
      script:
        - ./gradlew test
      after_success: ./gradlew coveralls uploadArchives
