language:
  - java
jdk:
  - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/72d92f6ecbc9b66f264c
    on_success: change
    on_failure: always
before_script:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
  - nvm install 0.12.4
  - nvm use 0.12.4
script: ./gradlew setupUiDev testAll
after_script:  ./gradlew jacocoTestReport coveralls 

