version: '3.8'

services:
  ipat-test-frontend-node:
    container_name: ipat-test-frontend-node
    image: ipat-test-frontend-node
    networks:
      - ipat-test-network
    
  ipat-test-nginx:
    container_name: ipat-test-nginx
    image: ipat-test-nginx
    ports:
      - 80:80
      - 443:443
    # depends_on:
    #   - ipat-test-api-user
    networks:
      - ipat-test-network

  ipat-test-api-user:
    container_name: ipat-test-api-user
    image: ipat-test-api-user
    command: sh -c "./gradlew user:bootRun"
    volumes:
      - ../admin/temp:/usr/src/app/admin/temp
    networks:
      - ipat-test-network
    depends_on:
      - ipat-test-mysql

  ipat-test-api-admin:
    container_name: ipat-test-api-admin
    image: ipat-test-api-admin
    command: sh -c "./gradlew admin:bootRun"
    volumes:
      - ../admin/temp:/usr/src/app/admin/temp
    networks:
      - ipat-test-network
    depends_on:
      - ipat-test-mysql

  ipat-test-api-article-manager:
    container_name: ipat-test-api-article-manager
    image: ipat-test-api-admin
    command: sh -c "./gradlew article-manager:bootRun"
    volumes:
      - ../admin/temp:/usr/src/app/admin/temp
    networks:
      - ipat-test-network
    depends_on:
      - ipat-test-mysql


  ipat-test-mysql:
    image: ipat-test-mysql
    container_name: ipat-test-mysql
    environment:
        MYSQL_DATABASE: ipat_2019
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./_mysql/dev-data:/var/lib/mysql/
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']
    networks:
      - ipat-test-network
  

networks:
  ipat-test-network:
    driver: bridge
